spring.application.name=itic
server.port=8085

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3311/db_ecomerce}
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:api_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

# IMPORTANT: Activar l'execució dels scripts SQL
#spring.sql.init.mode=always

# SQL logging
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# OAuth2 Google Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8085/login/oauth2/code/google

# AWS Cognito Configuration
aws.cognito.region=${AWS_COGNITO_REGION:eu-west-1}
aws.cognito.userPoolId=${AWS_COGNITO_USER_POOL_ID}
aws.cognito.clientId=${AWS_COGNITO_CLIENT_ID}
aws.cognito.jwks-url=https://cognito-idp.${aws.cognito.region}.amazonaws.com/${aws.cognito.userPoolId}/.well-known/jwks.json